# Generated by Django 4.1.6 on 2023-02-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earlyuser',
            old_name='favourite_story_type',
            new_name='storytype',
        ),
    ]
