# Generated by Django 4.1.6 on 2023-02-05 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_rename_favourite_story_type_earlyuser_storytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlyuser',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
